<font size=6 color=red>Ejercicios - Dia 6</font>

---

Declarar una lista vacía.

In [ ]:
marca_neumaticos = [
    'Michelin',
    'BFGoodrich',
    'tigar',
    'Dunlop',
    'Pirelli',
    'Continental'
]

---

Encuentra la longitud de tu lista.

In [ ]:
marca_neumaticos = [
    'Michelin',
    'BFGoodrich',
    'tigar',
    'Dunlop',
    'Pirelli',
    'Continental'
]

print(len(marca_neumaticos))

---

Obtenga el primer elemento, el elemento del medio y el último elemento de la lista.

In [2]:
marca_neumaticos = [
    'Michelin',
    'BFGoodrich',
    'tigar',
    'Dunlop',
    'Pirelli',
    'Continental'
]
longitud = len(marca_neumaticos)
mitad = longitud // 2

print(marca_neumaticos[0])
print(marca_neumaticos[mitad])
print(marca_neumaticos[-1])

Michelin
Dunlop
Continental

---

Declare una lista llamada tipos_de_datos_mixtos, ponga su (nombre, edad, altura, estado civil, dirección).

In [ ]:
tipos_de_datos_mixtos = ['Enrique', 47, 1.78, 'casado', 'Cordoba']

---

Declare una variable de lista llamada it_companies y asigne valores iniciales Facebook, Google, Microsoft, Apple, IBM, Oracle y Amazon.

In [ ]:
it_companies = [
    'Facebook',
    'Google',
    'Microsoft',
    'Apple',
    'IBM',
    'Oracle',
    'Amazon'
]

# Imprime la lista usando print().

print(it_companies)

# Imprimir el número de empresas en la lista.

print(len(it_companies))

# Imprimir la primera, segunda y última empresa.

print(it_companies[0])
print(it_companies[1])
print(it_companies[-1])

# Imprimir la lista después de modificar una de las empresas.

it_companies[1] = 'Michelin'
print(it_companies)

# Agregar una empresa de TI a it_companies

it_companies.append('Movistart')
print(it_companies)

# Inserte una empresa de TI en medio de la lista de empresas.

it_companies.insert(3, 'Tesla')
print(it_companies)

# Cambie uno de los nombres de it_companies a mayúsculas (IBM excluido!).

it_companies[3] = it_companies[3].upper()
print(it_companies)

# Compruebe si una determinada empresa existe en la lista it_companies.

if 'Google' in it_companies:
    print('Google se encuantra en la lista')
else:
    print('Google no se encuentra en la lista')

# Ordenar la lista usando el método sort().

it_companies.sort()
print(it_companies)

# Invierta la lista en orden descendente usando el método reverse().

it_companies.sort(reverse=True)
print(it_companies)

# Rebana las 3 primeras empresas de la lista.

print(it_companies[0:3])

# Rebana las últimas 3 empresas de la lista.

it_companies = [
    'Facebook',
    'Google',
    'Microsoft',
    'Apple',
    'IBM',
    'Oracle',
    'Amazon'
]

print(it_companies[-3:])

# Rebane la empresa o empresas intermedias de TI de la lista.

print(it_companies[3:5])

# Eliminar la primera empresa de TI de la lista.

it_companies = [
    'Facebook',
    'Google',
    'Microsoft',
    'Apple',
    'IBM',
    'Oracle',
    'Amazon'
]

del it_companies[0]
print(it_companies)

# Eliminar la empresa o empresas intermedias de TI de la lista.

it_companies = [
    'Facebook',
    'Google',
    'Microsoft',
    'Apple',
    'IBM',
    'Oracle',
    'Amazon'
]

del it_companies[3:5]
print(it_companies)

# Eliminar la última empresa de TI de la lista.

it_companies = [
    'Facebook',
    'Google',
    'Microsoft',
    'Apple',
    'IBM',
    'Oracle',
    'Amazon'
]

it_companies.pop()
print(it_companies)

# Eliminar todas las empresas de TI de la lista.

it_companies = [
    'Facebook',
    'Google',
    'Microsoft',
    'Apple',
    'IBM',
    'Oracle',
    'Amazon'
]

it_companies.clear()
print(it_companies)

# Destruye la lista de empresas de TI.

it_companies = [
    'Facebook',
    'Google',
    'Microsoft',
    'Apple',
    'IBM',
    'Oracle',
    'Amazon'
]

del it_companies

---

Unete las siguientes listas:

```python
front_end = ['HTML', 'CSS', 'JS', 'React', 'Redux']
back_end = ['Node', 'Express', 'MongoDB']
```

In [ ]:
front_end = ['HTML', 'CSS', 'JS', 'React', 'Redux']
back_end = ['Node', 'Express', 'MongoDB']

fusion = front_end + back_end
print(fusion)

---

Después de unir las listas, copie la lista unida y asígnela a una variable full_stack. Luego inserte Python y SQL después de Redux.

In [ ]:
front_end = ['HTML', 'CSS', 'JS', 'React', 'Redux']
back_end = ['Node', 'Express', 'MongoDB']

fusion = front_end + back_end

full_stack = fusion.copy()
full_stack.insert(5, 'Pyton')
full_stack.insert(6, 'SQL')
print(full_stack)

---

La siguiente es una lista de las edades de 10 estudiantes:

```python
ages = [19, 22, 19, 24, 20, 25, 26, 24, 25, 24]
```

Ordena la lista y encuentra la edad mínima y máxima.

In [ ]:
ages = [19, 22, 19, 24, 20, 25, 26, 24, 25, 24]

ages.sort()
print(ages)
print('La edad minima es:', min(ages))
print('La edad maxima es:', max(ages))

# Agregue la edad mínima y la edad máxima nuevamente a la lista.

edad_minima_maxima = [min(ages), max(ages)]
ages.extend(edad_minima_maxima)
print(ages)

---

Encuentre la edad promedio (suma de todos los elementos dividida por su número).

In [ ]:
ages = [19, 22, 19, 24, 20, 25, 26, 24, 25, 24]
suma = sum(ages)
num_items = len(ages)
print('La edad media es de:', suma / num_items)

---

Encuentre el rango de las edades (max menos min)

In [ ]:
ages = [19, 22, 19, 24, 20, 25, 26, 24, 25, 24]
ages.sort()
indice_menor = ages.index(min(ages))
indice_mayor = ages.index(max(ages))
print(ages[indice_menor+1:indice_mayor])

---

Dividir la lista de países en dos listas iguales, aunque no sea un país más para la primera mitad.

In [ ]:
paises = [
    'Afghanistan',
    'Albania',
    'Algeria',
    'Andorra',
    'Angola',
    'Antigua and Barbuda',
    'Argentina',
    'Armenia',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Bahamas',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belarus',
    'Belgium',
    'Belize',
    'Benin',
    'Bhutan',
    'Bolivia',
    'Bosnia and Herzegovina',
    'Botswana',
    'Brazil',
    'Brunei',
    'Bulgaria',
    'Burkina Faso',
    'Burundi',
    'Cambodia',
    'Cameroon',
    'Canada',
    'Cape Verde',
    'Central African Republic',
    'Chad',
    'Chile',
    'China',
    'Colombi',
    'Comoros',
    'Congo (Brazzaville)',
    'Congo',
    'Costa Rica',
    "Cote d'Ivoire",
    'Croatia',
    'Cuba',
    'Cyprus',
    'Czech Republic',
    'Denmark',
    'Djibouti',
    'Dominica',
    'Dominican Republic',
    'East Timor (Timor Timur)',
    'Ecuador',
    'Egypt',
    'El Salvador',
    'Equatorial Guinea',
    'Eritrea',
    'Estonia',
    'Ethiopia',
    'Fiji',
    'Finland',
    'France',
    'Gabon',
    'Gambia, The',
    'Georgia',
    'Germany',
    'Ghana',
    'Greece',
    'Grenada',
    'Guatemala',
    'Guinea',
    'Guinea-Bissau',
    'Guyana',
    'Haiti',
    'Honduras',
    'Hungary',
    'Iceland',
    'India',
    'Indonesia',
    'Iran',
    'Iraq',
    'Ireland',
    'Israel',
    'Italy',
    'Jamaica',
    'Japan',
    'Jordan',
    'Kazakhstan',
    'Kenya',
    'Kiribati',
    'Korea, North',
    'Korea, South',
    'Kuwait',
    'Kyrgyzstan',
    'Laos',
    'Latvia',
    'Lebanon',
    'Lesotho',
    'Liberia',
    'Libya',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Macedonia',
    'Madagascar',
    'Malawi',
    'Malaysia',
    'Maldives',
    'Mali',
    'Malta',
    'Marshall Islands',
    'Mauritania',
    'Mauritius',
    'Mexico',
    'Micronesia',
    'Moldova',
    'Monaco',
    'Mongolia',
    'Morocco',
    'Mozambique',
    'Myanmar',
    'Namibia',
    'Nauru',
    'Nepal',
    'Netherlands',
    'New Zealand',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'Norway',
    'Oman',
    'Pakistan',
    'Palau',
    'Panama',
    'Papua New Guinea',
    'Paraguay',
    'Peru',
    'Philippines',
    'Poland',
    'Portugal',
    'Qatar',
    'Romania',
    'Russia',
    'Rwanda',
    'Saint Kitts and Nevis',
    'Saint Lucia',
    'Saint Vincent',
    'Samoa',
    'San Marino',
    'Sao Tome and Principe',
    'Saudi Arabia',
    'Senegal',
    'Serbia and Montenegro',
    'Seychelles',
    'Sierra Leone',
    'Singapore',
    'Slovakia',
    'Slovenia',
    'Solomon Islands',
    'Somalia',
    'South Africa',
    'Spain',
    'Sri Lanka',
    'Sudan',
    'Suriname',
    'Swaziland',
    'Sweden',
    'Switzerland',
    'Syria',
    'Taiwan',
    'Tajikistan',
    'Tanzania',
    'Thailand',
    'Togo',
    'Tonga',
    'Trinidad and Tobago',
    'Tunisia',
    'Turkey',
    'Turkmenistan',
    'Tuvalu',
    'Uganda',
    'Ukraine',
    'United Arab Emirates',
    'United Kingdom',
    'United States',
    'Uruguay',
    'Uzbekistan',
    'Vanuatu',
    'Vatican City',
    'Venezuela',
    'Vietnam',
    'Yemen',
    'Zambia',
    'Zimbabwe',
]

print(len(paises))

# Funcion para dividir una lista por la mitad


def dividir_lista(lista):
    """Cuenta el numeto de elementos de la lista y la divide por la mitad con numero entero"""
    mitad = len(lista) // 2

    return lista[:mitad], lista[mitad:]  # Devuelve las dos mitades de la lista


# Asignamos dos variables y llamamos a la funcion con la lista que queremos dividir
b, c = dividir_lista(paises)

# Mostramos por pantalla la primera mitad de la lista
print('Primera mitad:\n', b)
print('\n')

# Mostramos por pantalla la segunda mitad de la lista
print('Segunda mitad:\n', c)

---

Encuentre el(los) país(es) intermedio(s) en la lista de países.

In [ ]:
x = len(paises) // 2
print('\nEl pais que se encuentra en mitad de la lista es:', paises[x])
print('\n')

---

```python
['China', 'Rusia', 'EE. UU.', 'Finlandia', 'Suecia', 'Noruega', 'Dinamarca']
```

Descomprima los primeros tres países y el resto como países escandinavos.

In [ ]:
paises = [
    'China',
    'Rusia',
    'EE.UU.',
    'Finlandia',
    'Suecia',
    'Noruega',
    'Dinamarca'
]

print('Paises no escandinavos:', paises[0:3])
print('Paises escandinavo:', paises[3:])